-- @label: revenue
SELECT P.CATEGORY                          AS CATEGORY,
       COUNT(DISTINCT O.ORDER_ID)          AS ORDERS,
       SUM(OI.QUANTITY)                    AS UNITS,
       SUM(OI.QUANTITY * OI.UNIT_PRICE_CENTS) AS REVENUE_CENTS
FROM ORDER_ITEMS OI
JOIN PRODUCTS P ON P.SKU = OI.SKU
JOIN ORDERS O   ON O.ORDER_ID = OI.ORDER_ID
WHERE O.STATUS IN ('paid', 'shipped')
GROUP BY P.CATEGORY
ORDER BY REVENUE_CENTS DESC;
